version: "3.1.1"

services:
  mysqldb:
    image: mysql:8.0.33
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    command: --innodb-redo-log-capacity=10485760
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    image: car-sharing-service
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "validate",
        "spring.jpa.show-sql" : "true",
        "jwt.expiration" : "$JWT_EXPIRATION",
        "jwt.secret" : "$JWT_SECRET",
        "bot.name" : "$BOT_NAME",
        "bot.key" : "$BOT_KEY",
        "stripe.api.key" : "$STRIPE_API_KEY",
        "stripe.success.link" : "http://localhost:$SPRING_LOCAL_PORT/payments/success?session_id={CHECKOUT_SESSION_ID}",
        "stripe.cancel.link" : "http://localhost:$SPRING_LOCAL_PORT/payments/cancel?session_id={CHECKOUT_SESSION_ID}"
        }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      BOT_KEY: "$BOT_KEY"
      BOT_NAME: "$BOT_NAME"
      JWT_SECRET: "$JWT_SECRET"
      STRIPE_API_KEY: "$STRIPE_API_KEY"

